services:
  postgres:
    image: postgres:16-alpine
    container_name: fintrack-db
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: fintrack_user
      POSTGRES_PASSWORD: fintrack_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: