spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}
