spring:
  application:
    name: fintrack-backend

  datasource:
    url: jdbc:postgresql://${FINTRACK_DB_HOST:localhost}:${FINTRACK_DB_PORT:5432}/${FINTRACK_DB_NAME:fintrack}?options=-c%20client_encoding%3DUTF8
    username: ${FINTRACK_DB_USERNAME:fintrack_user}
    password: ${FINTRACK_DB_PASSWORD:fintrack_pass}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "SET client_encoding = 'UTF8'"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${FINTRACK_SERVER_PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

jwt:
  secret: ${FINTRACK_JWT_SECRET:minha-chave-super-secreta-dev-trocar-em-producao-minimo-32-chars}
  expiration: ${FINTRACK_JWT_EXPIRATION:86400000}

cors:
  allowed-origins: ${FINTRACK_CORS_ORIGINS:http://localhost:4200}
